/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelebrationsRouteImport } from './routes/celebrations'
import { Route as HeroRouteImport } from './routes/hero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationsRoute = CelebrationsRouteImport.update({
  id: '/celebrations',
  path: '/celebrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroRoute = HeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebrations': typeof CelebrationsRoute
  '/hero': typeof HeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebrations': typeof CelebrationsRoute
  '/hero': typeof HeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebrations': typeof CelebrationsRoute
  '/hero': typeof HeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/celebrations' | '/hero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celebrations' | '/hero'
  id: '__root__' | '/' | '/celebrations' | '/hero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebrationsRoute: typeof CelebrationsRoute
  HeroRoute: typeof HeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrations': {
      id: '/celebrations'
      path: '/celebrations'
      fullPath: '/celebrations'
      preLoaderRoute: typeof CelebrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero': {
      id: '/hero'
      path: '/hero'
      fullPath: '/hero'
      preLoaderRoute: typeof HeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebrationsRoute: CelebrationsRoute,
  HeroRoute: HeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
